### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by tuchinsky** [chobostar/pgstats-to-clickhouse#1]
Could you provide json of your grafana dashboards from example screenshots? I mean graphs from this [screenshot](https://github.com/chobostar/pgstats-to-clickhouse/raw/master/examples/img/62add3afdb.png)

**Comment by chobostar** [comment]
@tuchinsky I have checked my archives, but unfortunately, the json is no longer available. 

However, you can refer to the [table schema](https://github.com/chobostar/pgstats-to-clickhouse/blob/master/db/migrations/clickhouse/init.sql#L35-L67) and use ChatGPT to help generate a ClickHouse SQL query for the Grafana plugin.
